### ISSUE TITLE
version missmatch

### ISSUE THREAD

**Issue by anujsr12** [javaducky/k6-office-hours-047#1]
![Screenshot from 2022-06-22 18-30-38](https://user-images.githubusercontent.com/50262640/175035243-017e0dcb-58aa-40f8-9236-1d33367b28ab.png)

**Comment by javaducky** [comment]
Hi @anujsr12 . You may need to upgrade your Docker Engine version. Based on the [compatibility matrix](https://docs.docker.com/compose/compose-file/compose-versioning/), version 3.8 used in `influxdb/docker-compose.yml` appears to be the most recent.

**Comment by anujsr12** [comment]
thanks for the help!!!!
